---
kubernetes_version: "v1.35"
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
kubernetes_common_packages:
  - apt-transport-https
  - ca-certificates
  - containerd
  - curl
  - gpg
kubernetes_kernel_modules:
  - overlay
  - br_netfilter
kubernetes_sysctl_settings:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"
containerd_config_path: /etc/containerd/config.toml
containerd_cri_socket: unix:///run/containerd/containerd.sock
kubernetes_keyring_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
kubernetes_apt_repo: "deb [signed-by={{ kubernetes_keyring_path }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
pod_network_cidr: 192.168.0.0/16
calico_manifest_url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml
control_plane_endpoint: "{{ hostvars[groups['kube_control_plane'][0]].ansible_host | default(hostvars[groups['kube_control_plane'][0]].ansible_default_ipv4.address) }}"
kubeconfig_user: "{{ ansible_user | default('ubuntu') }}"
