---
- name: Prepare all Kubernetes nodes
  hosts: kube_cluster
  become: true
  gather_facts: true
  roles:
    - role: sameer.kubernetes.kubeadm_common

- name: Initialize Kubernetes control plane
  hosts: kube_control_plane
  become: true
  gather_facts: true
  roles:
    - role: sameer.kubernetes.kubeadm_control_plane

- name: Join Kubernetes worker nodes
  hosts: kube_workers
  become: true
  gather_facts: true
  roles:
    - role: sameer.kubernetes.kubeadm_worker_join
