---
namespace: "sameer"
name: "kubernetes"
readme: README.md
version: 0.0.1
authors:
  - Sameer Alam

description: Local Ansible collection for kubeadm-based Kubernetes cluster setup
tags: ["kubernetes", "kubeadm", "containerd"]
repository: https://github.com/sameeralam/kubernetes-setup
